microsoft/BotBuilder-V3

README.md

- use V3 links for sdk, samples, issues, & docs

Update readme to fix links to use v3 resources

---

README.md

Fixed typo you -> your in readme.md

---

Node/Generator/package-lock.json
Node/Generator/package.json
Node/core/package-lock.json
Node/core/package.json

fix npm vulnerabilities in Node/*

---

CSharp/Library/Microsoft.Bot.Connector.AspNetCore/Microsoft.Bot.Connector.AspNetCore.csproj
CSharp/Library/Microsoft.Bot.Connector.AspNetCore/Microsoft.Bot.Connector.AspNetCore.nuspec
CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/Microsoft.Bot.Connector.AspNetCore2.csproj
CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/Microsoft.Bot.Connector.AspNetCore2.nuspec
CSharp/Library/Microsoft.Bot.Connector.Falcon/Microsoft.Bot.Connector.Falcon.csproj
CSharp/Library/Microsoft.Bot.Connector.Falcon/Microsoft.Bot.Connector.nuspec
CSharp/Library/Microsoft.Bot.Connector.Falcon/packages.config
CSharp/Library/Microsoft.Bot.Connector.NetCore/Content/Microsoft.Bot.Connector.NetCore.XML
CSharp/Library/Microsoft.Bot.Connector.NetCore/Microsoft.Bot.Connector.NetCore.csproj
CSharp/Library/Microsoft.Bot.Connector.NetCore/Microsoft.Bot.Connector.NetCore.nuget.props
CSharp/Library/Microsoft.Bot.Connector.NetCore/project.json
CSharp/Library/Microsoft.Bot.Connector.NetFramework/Content/Microsoft.Bot.Connector.xml
CSharp/Library/Microsoft.Bot.Connector.NetFramework/Microsoft.Bot.Connector.NetFramework.csproj
CSharp/Library/Microsoft.Bot.Connector.NetFramework/Microsoft.Bot.Connector.nuspec
CSharp/Library/Microsoft.Bot.Connector.NetFramework/packages.config
CSharp/Library/Microsoft.Bot.Connector.Shared/Authentication/AdalAuthenticator.cs
CSharp/Library/Microsoft.Bot.Connector.Shared/HttpClientEx.cs
CSharp/Library/Microsoft.Bot.Connector.Shared/JwtConfig.cs
CSharp/Library/Microsoft.Bot.Connector.Shared/MicrosoftAppCredentials.cs
CSharp/Library/Microsoft.Bot.Connector.Standard/Microsoft.Bot.Connector.Standard.csproj
CSharp/Tests/Microsoft.Bot.Builder.Tests/GetTokenRefreshTests.cs
CSharp/Tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
CSharp/Tests/Microsoft.Bot.Builder.Tests/packages.config

Also using the same rest.clientruntime version for all packages in solution.

C# Token Refresh: Upgrade from ADAL To MSAL, Lazy initialization of credential provider and nuspec updates

---

CSharp/Library/Microsoft.Bot.Builder.FormFlow.Json/FormBuilderJson.cs

Revert https://github.com/Microsoft/BotBuilder-V3/commit/c78b7d8c93560dffbffc43acccbdcf923fc71504 
It is causing high memory usage: https://github.com/Microsoft/BotBuilder-V3/issues/74

Fix FormBuilderJson high memory usage

---

CSharp/Library/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj

Missed with https://github.com/Microsoft/BotBuilder-V3/pull/78

add LuisDelegatingHandler to .csproj

---

Node/core/src/dialogs/LuisRecognizer.ts

ref: https://github.com/Microsoft/botbuilder-js/pull/677
addresses: https://github.com/Microsoft/BotBuilder-V3/issues/58

Add John Taylor's format for user-agent for node luis calls

---

Node/core/src/dialogs/IntentRecognizer.ts
Node/core/src/dialogs/LuisRecognizer.ts
Node/core/src/interfaces.d.ts

https://github.com/Microsoft/BotBuilder-V3/issues/64
and
https://github.com/Microsoft/BotBuilder-V3/issues/63

Add sentiment analysis and altered query to LuisResult for node sdk

---

Node/Generator/package-lock.json

The audit prepublish task in our daily Azure DevOps build identified new vulnerabilities across several npm packages. This pull request updates those packages and allows the audit task and build to succeed.

Update packages to fix security vulnerabilities

---

README.md

V3 deprecation message to help people migrate to V4 and stop V3 development.

added V3 deprecation message

---

README.md

Change verbiage according to team decision.

lifetime --> long-term

---

Node/core/lib/bots/ChatConnector.js
Node/core/src/bots/ChatConnector.ts

This is a needed follow up to the following closed pull request:
https://github.com/microsoft/BotBuilder-V3/pull/144
I had made the original changes to the Javascript file directly, before I understood how TypeScript was being used in the project. This PR makes the changes in the src TypeScript file so that they're then transpiled and output to JS (and won't be overwritten next time the TS file changes).

403 error handling to ts

---

Node/core/lib/bots/ChatConnector.js
Node/core/lib/consts.js

Transpiling TypeScript changes to JS, for updates to ChatConnector.ts
On April 9, changes to TS files were committed but corresponding transpiled JS changes were not:
https://github.com/microsoft/BotBuilder-V3/pull/80
Any further changes to ChatConnector.ts will see these changes reflected in the JS output, so we need to go ahead and merge them in to get everything back in sync.

Transpiling TS changes to JS and adding to repo

---

CSharp/Library/Microsoft.Bot.Connector.NetFramework/Content/Microsoft.Bot.Connector.xml
CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/Activity.cs
CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/AttachmentView.cs
CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json

Add CallerId to Activity
Update comments of AttachmentView

ConnectorAPI swagger updates

---

CSharp/Samples/AadV1Bot/Controllers/MessagesController.cs
CSharp/Samples/AadV1Bot/Dialogs/RootDialog.cs
CSharp/Samples/AadV1Bot/Global.asax.cs
CSharp/Samples/AadV1Bot/Microsoft.Bot.Sample.AadV1Bot.csproj
CSharp/Samples/AadV1Bot/packages.config
CSharp/Samples/AadV2Bot/Controllers/MessagesController.cs
CSharp/Samples/AadV2Bot/Dialogs/RootDialog.cs
CSharp/Samples/AadV2Bot/Global.asax.cs
CSharp/Samples/AadV2Bot/Microsoft.Bot.Sample.AadV2Bot.csproj
CSharp/Samples/AadV2Bot/packages.config

Fix memory store registration for AAD samples.  Remove calls to GetManager. Upgrade package references.

Fix AAD samples

---

Node/Generator/package-lock.json

The security audit run by this build found vulnerabilities:
https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=72929
This pr fixes those by updating the affected packages.

Updating dependencies for security audit

---

Node/Generator/package-lock.json

Ran "npm audit fix" per instructions in the failed build BotBuilder-v3-JS-CI #6 https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=97830&view=results[](url)

Fix 10 vulnerabilities.

---

CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/ResumptionContext.cs

Removes broken doc xml links

---

CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/Microsoft.Bot.Connector.AspNetCore2.nuspec

Needed for publishing symbol files per issue #3599

Add .pdb reference to .nuspec

---

CSharp/Library/Microsoft.Bot.Connector.Shared/MicrosoftAppCredentials.cs
CSharp/Tests/Microsoft.Bot.Builder.Tests/GetTokenRefreshTests.cs

This reverts commit 98a5d5975e7ef77d4de48d6e81d86ca07659424c.

Revert "Enable multiple scopes for single serviceUrl host (#215)"
